### ISSUE TITLE
Infoblox provider config not working

### ISSUE THREAD

**Issue by iaean** [dns3l/dns3l-core#10]
When I try to configure an Infoblox provider
```yaml
dns:
  providers:
    infblx:
      type: infblx
      name: Infoblox
      host: localhost
```

the server dies with the message
```
panic: no DNS provider found for infblx
```

Thx 4 investigation
