### ISSUE TITLE
logopath does not support relative/absolute paths, only URLs

### ISSUE THREAD

**Issue by iaean** [dns3l/dns3l-core#11]
When I try to configure a URL path as `LogoPath` like
```yaml
ca:
  providers:
    le:
      type: acme
      name: "Let's Encrypt"
      logopath: /le.png
```

the server dies with the following message
```
Key: 'Config.CA.Providers[le].Prov.C.LogoPath' Error:Field validation for 'LogoPath' failed on the 'url' tag
```

Thx 4 investigation
