### ISSUE TITLE
OIDC tocken issuer check problems

### ISSUE THREAD

**Issue by iaean** [dns3l/dns3l-core#19]
I try to run `dns3ld` together with `dex` on a stack or cluster beyond an ingress proxy.

The OIDC provider needs to publish his (external) issuer URL to support foreign clients like CLI or web apps.

`dns3ld` maybe needs to establish a connection to the cluster/stack (internal) dex endpoint and complains with

```
panic: oidc: issuer did not match the issuer returned by provider, expected "https://auth:5554/auth" got "https://dns3l.example.com/auth"
```

If `dns3ld` has no outbound connectivity to the external endpoint then it seems not possible to run it together with `dex` inside a cluster.

```yaml
# dns3ld config
auth:
  issuer: https://auth:5554/auth
  http_insecure_skip_verify: true

# dex config
issuer: https://dns3l.example.com/auth
```

**Comment by lnobach** [comment]
It should work when you set `https://dns3l.example.com/auth` unter auth.issuer, not the internal DNS name, so it goes through the proxy.

The OIDC plugin only supports disabling the endpoint URL entirely, which is insecure.

**Comment by iaean** [comment]
Can we pass through disabling URL checking to our users, pls? E.g.

```yaml
auth:
  oidc_issuer_url_check: false # default: true
```

We are not controlling users proxy/lb infra. So this will popping up...

**Comment by iaean** [comment]
`dns3ld` is dying when the issuer URL retrieved from the OIDC provider is not configured in `dns3ld`.

In multihomed deployments you will receive valid tokens with different `iss` produced by the same auth subsystem.

As workaround the check should be disabled by config.
As fix you need to support different issuer URL. E.g.

```yaml
# dns3ld config
auth:
  issuer:
  - https://dns3l.example.com/auth
  - https://dns3l.foo.example.com/auth
  - https://dns3l.bar.example.com/auth
  oidc_issuer_url_check: false # default: true
  http_insecure_skip_verify: true # default false

# dex config
issuer: https://dns3l.example.com/auth
issuer: https://dns3l.foo.example.com/auth
issuer: https://dns3l.bar.example.com/auth
```
