### ISSUE TITLE
TCP connect timeout too long

### ISSUE THREAD

**Issue by iaean** [dns3l/dns3l-core#33]
If the IP of an OIDC provider is not reachable, seems there is a long TCP connect timeout independent of `force_on_startup`. Maybe we can decrease the default and make it configurable.

```yaml
auth:
  oidc_bindings:
    https://auth:5554/auth:
      force_on_startup: true
    https://dns3l.example.com/auth:
      force_on_startup: false
```

Expected behaviour:

```
level=error msg="Error while initializing new provider, will retry with next request." error="Get \"https://dns3l.example.com/auth/.well-known/openid-configuration\": dial tcp 172.22.0.7:443: connect: connection refused" issuerURL="https://dns3l.example.com/auth" module=auth
level=info msg="Successfully initialized new OIDC provider." issuerURL="https://auth:5554/auth" module=auth
level=info msg="Service starting..." module=service
```

To reproduce configure an OIDC provider URL that resolves to an IP that is not reachable.
