### ISSUE TITLE
Daemon publishing incorrect CA config

### ISSUE THREAD

**Issue by iaean** [dns3l/dns3l-core#60]
Even if a CA is configured as `disabled`
```yaml
ca:
  providers:
    id:
      type: acme
      catype: public
      enabled: false
```
it is populated as `enabled`
```json
{
  "id": "id",
  "type": "public",
  "acme": true,
  "enabled": true
}
```
This is breaking clients that rely on that. Daemon version: `1.1.4`.

In the same context it would be great if we can ensure that an error is raised to the client if he tries to utilize a `disabled` CA. Maybe we ensure also that a `rtzn` is never pinned to a `disabled` CA resulting in `rtzn: []`.
