### ISSUE TITLE
Add wildcard and SAN capability to CA provider config

### ISSUE THREAD

**Issue by iaean** [dns3l/dns3l-core#64]
Just redirecting error messages from backend libs or backends like CA to the client aka server is often confusing.
We have CA that is not supporting wildcards. An error message like `Sorry. Error #0` is redirected to the client.

It would be great to add `wildcards` and `sans` to CA provider config
```yaml
ca:
  providers:
    id:
      wildcards: false # default true
      sans: false # default true
```
and offer better error messages via API if the client tries to claim where it is not available.
And the client can try to ensure that wildcards are not usable for that CA.
